version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "updating git ..."; apt-get update; apt-get install -y
        python-software-properties software-properties-common;
        add-apt-repository ppa:git-core/ppa; apt-get update; apt-get install -y
        git
      - echo "machine github.com login unused password ${GH_TOKEN}" > ~/.netrc
      - echo "//npm.pkg.github.com/:_authToken=${GH_TOKEN}" > ~/.npmrc
      - npm install -g npm@
      - export GK_LOCK_DEFAULT_BRANCH=saga
      - npm i -g greenkeeper-lockfile@2
      - npx greenkeeper-lockfile-update
      - npm ci --no-audit
  pre_build:
    commands:
      - npm run lint
      - npx tsc
      - export STACK_BASE_NAME=bdd-feature-runner-aws-example-$(node -e
        'process.stdout.write(Math.random().toString(36).replace(/[^a-z]+/g,
        ""))')
      - npx cdk deploy --require-approval never
  build:
    commands:
      - npm test
      - npx greenkeeper-lockfile-upload
      - npm i semantic-release; npx semantic-release || true
  post_build:
    commands:
      - npx cdk destroy -f
